//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ELabs
{
    using System;
    using System.Collections.Generic;
    
    public partial class equipo
    {
        public string serie { get; set; }
        public string observaciones { get; set; }
        public int laboratorio_num_fk { get; set; }
        public string laboratorio_edificio_fk { get; set; }
        public string t_equipo_fk { get; set; }
        public string e_equipo_fk { get; set; }
    
        public virtual laboratorio laboratorio { get; set; }
        public virtual estado_equipo estado_equipo { get; set; }
        public virtual tipo_equipo tipo_equipo { get; set; }
    }
}
