//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ELabs
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class elabsDB : DbContext
    {
        public elabsDB()
            : base("name=elabsDB")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<edificio> edificio { get; set; }
        public virtual DbSet<equipo> equipo { get; set; }
        public virtual DbSet<estado> estado { get; set; }
        public virtual DbSet<estado_equipo> estado_equipo { get; set; }
        public virtual DbSet<laboratorio> laboratorio { get; set; }
        public virtual DbSet<reserva> reserva { get; set; }
        public virtual DbSet<tipo_equipo> tipo_equipo { get; set; }
        public virtual DbSet<usuario> usuario { get; set; }
    }
}
