//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ELabs
{
    using System;
    using System.Collections.Generic;
    
    public partial class reserva
    {
        public int identificador { get; set; }
        public string usuario_fk { get; set; }
        public System.DateTime fecha_inicio { get; set; }
        public System.DateTime fecha_fin { get; set; }
        public int laboratorio_num_fk { get; set; }
        public string laboratorio_edificio_fk { get; set; }
    
        public virtual laboratorio laboratorio { get; set; }
        public virtual usuario usuario { get; set; }
    }
}
